service: TccShop
plugins:
  - serverless-s3-sync

custom:
  siteName: tccshop.com.br
  hostedZoneName: tccshop.com.br
  aliasHostedZoneId: Z2O1EMRO9K5GLX    # us-east-2
  aliasDNSName: s3-website.us-east-2.amazonaws.com
  s3Sync:
    - bucketName: ${self:custom.hostedZoneName}
      localDir: ../frontend/build


# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]     