
service: autenticacao # NOTE: update this with your service name


custom:
  tableName: 'Usuarios-${self:provider.stage}'


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  environment:
    USUARIOS_TABLE: ${self:custom.tableName}
    AWS_DEPLOY_REGION: ${self:provider.region}
    JWT_ENCRYPTION_CODE: "CE2784CB-EFF6-4AFB-A56F-5EF156E85F80"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["Usuarios", "Arn" ] }
        - { "Fn::Join": [ "/", [ 
           { "Fn::GetAtt": ["Usuarios", "Arn" ] }, "index", "roomIndex" 
          ]]}
        - { "Fn::Join": [ "/", [
            { "Fn::GetAtt": ["Usuarios", "Arn" ] }, "index", "userIndex" 
          ]]}

functions:
  login:
    handler: handler.authenticate
    memorySize: 128
    events:
      - http: 
          method: POST
          path: /login
          private: false
  createUser:
    handler: handler.createUser
    memorySize: 128
    events:
      - http: 
          method: POST
          path: /users
          private: false
  deleteUser:
    handler: handler.deleteUser
    memorySize: 128
    events:
      - http: 
          method: DELETE
          path: /users
          private: false

resources:
  Resources:
    Usuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: username-index
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

