export const Types = {
  LOADING_DATA: 'LOADING_DATA',
  DATA_RECEIVED: 'DATA_RECEIVED',
  SHOW_MESSAGE: 'SHOW_MESSAGE',
  CLOSE_MESSAGE: 'CLOSE_MESSAGE',
  REDIRECT_TO: 'REDIRECT_TO',
  REDIRECT_CLEAR: 'REDIRECT_CLEAR'
}
