export const Types = {
    PRODUTO_REFRESH: 'PRODUTO_REFRESH',
    PRODUTO_LOAD: 'PRODUTO_LOAD',
    LOADING_DATA:  'LOADING_DATA',
    SHOW_MESSAGE:  'SHOW_MESSAGE',
    DATA_RECEIVED:  'DATA_RECEIVED'
}